### PR TITLE
Do not encrypt when there was an error

### PR DESCRIPTION
**Pull request by hazcod**

### CODE REVIEW

**Comment by meehow** [comment]
Thank you for the contribution!
Just short question: isn't empty string encoded to empty string in base64 anyway?

**Comment by hazcod** [comment]
We might want to prevent cases where `err` was not nil, but a ciphertext was returned anyway.

**Comment by meehow** [comment]
gcm.Seal (which creates ciphertext) does not return any error https://github.com/meehow/securebytes/blob/master/main.go#L54

**Comment by hazcod** [comment]
Ahh, you’re right! Thanks.

**Comment by meehow** [comment]
Thank you for the contribution anyway. You were the first one! Highly appreciated.

**Pull request closed without merging**
